/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexion.Conector;
import controller.UsuarioController;
import dao.UsuariosDAO;
import java.sql.Connection;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Usuario
 */
public class CrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        barra_superior = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        label_usuario = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        label_contra = new javax.swing.JLabel();
        contra = new javax.swing.JTextField();
        label_confirma_contra = new javax.swing.JLabel();
        confirmacion = new javax.swing.JTextField();
        boton_crear_cuenta = new javax.swing.JToggleButton();
        cancelar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(770, 383));
        background.setPreferredSize(new java.awt.Dimension(770, 383));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra_superior.setBackground(new java.awt.Color(33, 159, 166));

        titulo.setFont(new java.awt.Font("Lobster", 0, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Genshin Artifacts");

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo_chiquito.jpg"))); // NOI18N

        javax.swing.GroupLayout barra_superiorLayout = new javax.swing.GroupLayout(barra_superior);
        barra_superior.setLayout(barra_superiorLayout);
        barra_superiorLayout.setHorizontalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addGap(119, 119, 119))
        );
        barra_superiorLayout.setVerticalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        background.add(barra_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 110));

        label_usuario.setText("Usuario");
        background.add(label_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));
        background.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 140, -1));

        label_contra.setText("Contraseña");
        background.add(label_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));
        background.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 140, -1));

        label_confirma_contra.setText("Confirme su Contraseña");
        background.add(label_confirma_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));
        background.add(confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 140, -1));

        boton_crear_cuenta.setText("Crear Cuenta");
        boton_crear_cuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_crear_cuentaMouseClicked(evt);
            }
        });
        background.add(boton_crear_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });
        background.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_crear_cuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_crear_cuentaMouseClicked
        
        
        if (usuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Su usuario está vacío.");
        } else if (contra.getText().isEmpty() || confirmacion.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Su contraseña o confirmación de contraseña están vacías.");
        }else if (!contra.getText().equals(confirmacion.getText())) {
            JOptionPane.showMessageDialog(this, "Su contraseña y confirmación no coinciden, reviselas.");
        }else{
            
            
            UsuariosDAO usuarioDAO = new UsuariosDAO();
            
            UsuarioController uctr = new UsuarioController(usuarioDAO);
            
            Usuario user = new Usuario();
            user.setUsuario(usuario.getText());

            if(!uctr.cuentaRepetida(user)){
                user.setUsuario(usuario.getText()); 
                user.setContrasenha(contra.getText());
                user.setId_tipos_cuenta(1);
                uctr.crearCuenta(user);
            
                
                JOptionPane.showMessageDialog(this, "Su cuenta fue creada con éxito.");
                this.setVisible(false);
                Login login = new Login();
                login.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "El usuario ya existe, pruebe con otro.");
            }
            
            
        }
        
        
    }//GEN-LAST:event_boton_crear_cuentaMouseClicked

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_cancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel barra_superior;
    private javax.swing.JToggleButton boton_crear_cuenta;
    private javax.swing.JToggleButton cancelar;
    private javax.swing.JTextField confirmacion;
    private javax.swing.JTextField contra;
    private javax.swing.JLabel label_confirma_contra;
    private javax.swing.JLabel label_contra;
    private javax.swing.JLabel label_usuario;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
