/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ArtefactoController;
import controller.CuentaIdController;
import controller.StatPrincipalController;
import controller.StatSecundarioController;
import controller.SubStatValoresController;
import controller.SubStatsSubidosController;
import controller.SubidasController;
import controller.TipoArtefactoController;
import controller.TipoArtefactoStatController;
import controller.TipoSetController;
import dao.ArtefactoDAO;
import dao.CuentaIdDAO;
import dao.StatPrincipalDAO;
import dao.StatSecundarioDAO;
import dao.SubStatValoresDAO;
import dao.SubStatsSubidosDAO;
import dao.SubidasDAO;
import dao.TipoArtefactoDAO;
import dao.TipoArtefactoStatDAO;
import dao.TipoSetDAO;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.StatPrincipal;
import modelo.StatSecundario;
import modelo.Subidas;
import modelo.TipoArtefacto;
import modelo.TipoSet;

/**
 *
 * @author Usuario
 */
public class Creacion extends javax.swing.JDialog {

    /**
     * Creates new form creacion
     */ 
    public Creacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    Creacion() { 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgorund = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<TipoSet>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<TipoArtefacto>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<StatPrincipal>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<StatSecundario>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<StatSecundario>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<StatSecundario>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<StatSecundario>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<Subidas>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<Subidas>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<Subidas>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<Subidas>();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        backgorund.setBackground(new java.awt.Color(255, 255, 255));
        backgorund.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Set");
        backgorund.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        backgorund.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 210, -1));
        TipoSetDAO tiposetDAO = new TipoSetDAO();
        TipoSetController tpsc = new TipoSetController(tiposetDAO);

        jComboBox1.addItem(new TipoSet(0, "Elige un Set"));
        List<TipoSet> tiposet = tpsc.listar();
        tiposet.forEach(tipos -> jComboBox1.addItem(tipos));

        jLabel2.setText("Tipo de artefacto");
        backgorund.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        backgorund.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, -1));
        TipoArtefactoDAO tipoartefactoDAO = new TipoArtefactoDAO();
        TipoArtefactoController tac = new TipoArtefactoController(tipoartefactoDAO);
        jComboBox2.addItem(new TipoArtefacto(0, "Elige la Pieza"));

        List<TipoArtefacto> tipoartefacto = tac.listar();
        tipoartefacto.forEach(tipos -> jComboBox2.addItem(tipos));

        jLabel3.setText("Stat Principal");
        backgorund.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jComboBox3.setMaximumRowCount(5);
        jComboBox3.setName(""); // NOI18N
        jComboBox3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox3PopupMenuWillBecomeVisible(evt);
            }
        });
        backgorund.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 180, -1));
        StatPrincipalDAO statprincipalDAO = new StatPrincipalDAO();
        StatPrincipalController stp = new StatPrincipalController(statprincipalDAO);

        jComboBox3.addItem(new StatPrincipal(0, "Elige la Estadística"));
        List<StatPrincipal> statprincipal = stp.listar();
        statprincipal.forEach(tipos -> jComboBox3.addItem(tipos));

        jLabel4.setText("Stat secundario 1");
        backgorund.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 20));
        backgorund.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));
        StatSecundarioDAO statsecundarioDAO = new StatSecundarioDAO();
        StatSecundarioController stsc = new StatSecundarioController(statsecundarioDAO);

        jComboBox4.addItem(new StatSecundario(0, "Elige un Substat"));
        List<StatSecundario> statsecundario = stsc.listar();
        statsecundario.forEach(tipos -> jComboBox4.addItem(tipos));

        jLabel5.setText("stat secundario 2");
        backgorund.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        backgorund.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));
        jComboBox5.addItem(new StatSecundario(0, "Elige un Substat"));
        statsecundario.forEach(tipos -> jComboBox5.addItem(tipos));

        jLabel6.setText("Stat secundario 3");
        backgorund.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        backgorund.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));
        jComboBox6.addItem(new StatSecundario(0, "Elige un Substat"));
        statsecundario.forEach(tipos -> jComboBox6.addItem(tipos));

        jLabel7.setText("Stat secundario 4");
        backgorund.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        backgorund.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));
        jComboBox7.addItem(new StatSecundario(0, "Elige un Substat"));
        statsecundario.forEach(tipos -> jComboBox7.addItem(tipos));

        jLabel8.setText("Veces subidas");
        backgorund.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));
        backgorund.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));
        SubidasDAO subidasDAO = new SubidasDAO();
        SubidasController sbd = new SubidasController(subidasDAO);

        List<Subidas> subidas = sbd.listar();
        subidas.forEach(tipos -> jComboBox8.addItem(tipos));

        jLabel9.setText("Veces subidas");
        backgorund.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));
        backgorund.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));
        subidas.forEach(tipos -> jComboBox9.addItem(tipos));

        jLabel10.setText("Veces subidas");
        backgorund.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));
        backgorund.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));
        subidas.forEach(tipos -> jComboBox10.addItem(tipos));

        jLabel11.setText("Veces subidas");
        backgorund.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));
        backgorund.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));
        subidas.forEach(tipos -> jComboBox11.addItem(tipos));

        Guardar.setText("Guardar");
        Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarMouseClicked(evt);
            }
        });
        backgorund.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        Cancelar.setText("Cancelar");
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
        });
        backgorund.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgorund, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgorund, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox3PopupMenuWillBecomeVisible
        TipoArtefacto v = (TipoArtefacto) jComboBox2.getSelectedItem();
        if (v.getId()!=0) {
            
            StatPrincipalDAO statprincipalDAO = new StatPrincipalDAO();
            StatPrincipalController stp = new StatPrincipalController(statprincipalDAO);
            jComboBox3.removeAllItems();

            jComboBox3.addItem(new StatPrincipal(0, "Elige la Estadística"));
            List<StatPrincipal> statprincipal = stp.listar(v);
            statprincipal.forEach(tipos -> jComboBox3.addItem(tipos)); 
        }
    }//GEN-LAST:event_jComboBox3PopupMenuWillBecomeVisible

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_CancelarMouseClicked

    private void GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseClicked
 
        crearArtefactoConSubstats();
        
    }//GEN-LAST:event_GuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                Creacion dialog = new Creacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }
    
    private boolean crearArtefacto(){
        boolean resultado;
        //crear artefacto
        ArtefactoDAO artefactoDAO = new ArtefactoDAO();
        ArtefactoController arc = new ArtefactoController(artefactoDAO);
        
            //traer la cuenta logeada
            CuentaIdDAO cuentaidDAO = new CuentaIdDAO();
            CuentaIdController cid = new CuentaIdController(cuentaidDAO);

            Integer cuentaid = cid.traerCuentaId();
            
            //Tipo set
            TipoSet ts = (TipoSet) jComboBox1.getSelectedItem();
            
            //Tipo artefacto y Stat principal
            TipoArtefacto tp = (TipoArtefacto) jComboBox2.getSelectedItem();
            StatPrincipal sp = (StatPrincipal) jComboBox3.getSelectedItem();
            
            
            
            TipoArtefactoStatDAO tipoartefactostatDAO = new TipoArtefactoStatDAO();
            TipoArtefactoStatController tas = new TipoArtefactoStatController(tipoartefactostatDAO);
            //Traer el Id del tipo_artefacto_stat
            Integer tipoartefactostat = tas.traerTipoArtefactoStat(tp.getId(), sp.getId());
        
            
            
            if (cuentaid !=0 && ts.getId() !=0 && tipoartefactostat !=0) {
             
             arc.guardarArtefactoNuevo(cuentaid, ts.getId(), tipoartefactostat);
             resultado= true;
            } else {
                JOptionPane.showMessageDialog(this, "Asegurese de llenar todos los campos correctamente");
                resultado = false;
            }
        
        
        return resultado;
    }
       
    private void crearArtefactoConSubstats(){
        
        //traer el artefacto recien creado
        ArtefactoDAO artefactoDAO = new ArtefactoDAO();
        ArtefactoController arc = new ArtefactoController(artefactoDAO);
            //traer la cuenta logeada
            CuentaIdDAO cuentaidDAO = new CuentaIdDAO();
            CuentaIdController cid = new CuentaIdController(cuentaidDAO);

            Integer cuentaid = cid.traerCuentaId();
        

        //substats subidos
        StatSecundario st1 = (StatSecundario) jComboBox4.getSelectedItem();
        StatSecundario st2 = (StatSecundario) jComboBox5.getSelectedItem();
        StatSecundario st3 = (StatSecundario) jComboBox6.getSelectedItem();
        StatSecundario st4 = (StatSecundario) jComboBox7.getSelectedItem();
        
        //cantidad de subidas
        Subidas sb1 = (Subidas) jComboBox8.getSelectedItem();
        Subidas sb2 = (Subidas) jComboBox9.getSelectedItem();
        Subidas sb3 = (Subidas) jComboBox10.getSelectedItem();
        Subidas sb4 = (Subidas) jComboBox11.getSelectedItem();
        
        int suma = sb1.getCantidad()+sb2.getCantidad()+sb3.getCantidad()+sb4.getCantidad();
        //validar que las veces subidas sean validas
        if (suma>4) {
            JOptionPane.showMessageDialog(this, "La suma de cantidades subidas no puede ser mayor a 4.");
        } else if (suma < 3) {
            JOptionPane.showMessageDialog(this, "La suma de cantidades subidas no puede ser menor a 3.");
        } else if (st1.getId()==0 && st2.getId()==0 && st3.getId()==0 && st4.getId()==0){
            JOptionPane.showMessageDialog(this, "Selecicone todos los 4 sub stats de su artefacto");
        }else {
            if (crearArtefacto()) {
                SubStatValoresDAO substatvaloresDAO = new SubStatValoresDAO();
                SubStatValoresController stv = new SubStatValoresController(substatvaloresDAO);

                    //traer los ids de la combinación entre substat y su valor
                    Integer substatvalores1 = stv.traerSubStatValor(st1.getId());
                    Integer substatvalores2 = stv.traerSubStatValor(st2.getId());
                    Integer substatvalores3 = stv.traerSubStatValor(st3.getId());
                    Integer substatvalores4 = stv.traerSubStatValor(st4.getId());
                    //traer los ids de la cantidad subida
                    Integer cantidadsubidas1 = sb1.getId();
                    Integer cantidadsubidas2 = sb2.getId();
                    Integer cantidadsubidas3 = sb3.getId();
                    Integer cantidadsubidas4 = sb4.getId();

                    //Arterfacto recien guardado
                    Integer idArtefacto=arc.idUltimoArtefacto(cuentaid);
                    
                SubStatsSubidosDAO substatssubidosDAO = new SubStatsSubidosDAO();
                SubStatsSubidosController sbsc = new SubStatsSubidosController(substatssubidosDAO);

                sbsc.guardarSubstatsSubidos(idArtefacto, substatvalores1, cantidadsubidas1);
                sbsc.guardarSubstatsSubidos(idArtefacto, substatvalores2, cantidadsubidas2);
                sbsc.guardarSubstatsSubidos(idArtefacto, substatvalores3, cantidadsubidas3);
                sbsc.guardarSubstatsSubidos(idArtefacto, substatvalores4, cantidadsubidas4);
                JOptionPane.showMessageDialog(this, "Artefacto guardado con éxito");
                this.dispose();
            }

        }
        
        
    }
        
    
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Cancelar;
    private javax.swing.JButton Guardar;
    private javax.swing.JPanel backgorund;
    private javax.swing.JComboBox<TipoSet> jComboBox1;
    private javax.swing.JComboBox<Subidas> jComboBox10;
    private javax.swing.JComboBox<Subidas> jComboBox11;
    private javax.swing.JComboBox<TipoArtefacto> jComboBox2;
    private javax.swing.JComboBox<StatPrincipal> jComboBox3;
    private javax.swing.JComboBox<StatSecundario> jComboBox4;
    private javax.swing.JComboBox<StatSecundario> jComboBox5;
    private javax.swing.JComboBox<StatSecundario> jComboBox6;
    private javax.swing.JComboBox<StatSecundario> jComboBox7;
    private javax.swing.JComboBox<Subidas> jComboBox8;
    private javax.swing.JComboBox<Subidas> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
